### ISSUE TITLE
Markdown Display Issues & Host Dependency issues

### ISSUE THREAD

**Issue by rlthompson904** [MicrosoftLearning/MS-030-Office365Administrator#1]
# Module: All
#### Step: 00

Description of issue

- All Instructions are indented leading to markdown display issues. 

-Mentions **Sign in with the O365 Credentials located in the top right corner under the Files drop down menu.**  on Module 1 task 1 step 3

-Mentions Xtreme labs throughout instruction. 

- No Heading in Module 11

**Comment by geschwei** [comment]
all issues that have been identified have been resolved. thank you for pointing these discrepancies out.

**Comment by rlthompson904** [comment]
Xtr3m3L@bs used as password still in Modules 5,7,9,10.
