### ISSUE TITLE
Lab 02 Some exercise and task numbers missing.

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-030-Office365Administrator#21]
# Module: 02
#### Step: 00

Description of issue

Several of the exercise numbers and task numbers are missing in the lab instructions.

Repro steps:

1.
1.
1.

**Comment by AnnetteGill** [comment]
The other problem with this version of the labs is that the lab numbering/lettering doesn't match what's in the PPT slides, the SkillPipe course manual and the trainer handbook.

For example, in Module 2, the labs are as follows:

Lab 2A, exercises 1 and 2
Lab 2B, exercises 1, 2 and 3

In the PPT slides, the Skillpipe course book, the Trainer Handbook preview and the version of these labs that were posted here earlier this week, the labs are:

Lab 2, exercise 1
Lab 2, exercise 2
Lab 2, exercise 3
Lab 2, exercise 4
Lab 2, exercise 5

Why have the lab numbers/letters been changed, so they no longer match the rest of the course materials?

**Comment by geschwei** [comment]
this is resolved in the updates that will be published today.
