### ISSUE TITLE
Custom domain inconsistencies

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-030-Office365Administrator#22]
# Module: 01 and 03
#### Step: 00

Description of issue
In Lab 01, the custom domain you add is called ZZZZZZ.Hostdomain.  You verify this by adding a TXT record.  Then you add an A record and an MX record.

In Lab 02, the custom domian is referred to as XXYYZZa.xtremelabs.us

In Lab 03, the custom domain is now referred to as M365xyyxxxxx.hostdomain.com.  Among other records, you have to add an MX record for the domain - again!

Repro steps:

1.
1.
1.

**Comment by TesterTesterson1004** [comment]
I agree that the various 'placeholder' names used for 'tenant.onmicrosoft.com', as opposed to the custom domain could use some checking and standardization throughout all docs to insure they are used consistently.

In addition to the ones mentioned above, I would add that in Lab 02/various Tasks, there is yet another distinct variation: 'yourdomain.hostdomain.com' that appears to be used in several places as a placeholder.

For example:  

- In Lab 02/Exercise 1/ User Libby Howard is created clearly as a 'M365xZZZZZZ.**onmicrosoft.com**' domain user.  Slightly later in 'Task : Verifying user settings' Step 2 we are told to login as Libby using 'libby@**yourdomain.hostdomain.com**'. then in step 9 as 'Libb@M365xZZZZZZ. **hostdomain.com**'.  Subsequent steps have users 'Admin@M365xZZZZZZ.onmicrosoft.com', & 'Alan@M365xZZZZZZ. hostdomain.com'.

- In Lab 02/Exercise 2/'Task 2: Create new users and assign licenses by using Windows PowerShell' the cmds all appear to use the yourdomain.hostdomain.com:

![image](https://user-images.githubusercontent.com/49700217/94204879-f2b89300-fe76-11ea-918c-cc6de742f5c0.png)

  I *think* in these places, in the context of the surrounding tasks/steps, that the usage of 'yourdomain.hostdomain.com' *should* more consistently be generically labeled 'M365xZZZZZZ.onmicrosoft.com'.  

On the other hand, given the previous usage of the 'ZZZZZZ.Hostdomain' to be used for the **custom domain**, I am not sure.

**Comment by geschwei** [comment]
thanks for the comments regarding the agnostic variations we use to distinguish between the Tenant domain (M365xzzzzz.onmicrosoft.com) and the custom domain (your domain.hostdomain.com) in this update we are making a more consistent picture for our instructions.
