### ISSUE TITLE
Lab 4 IdFix link is wrong

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-030-Office365Administrator#23]
# Module: 04
#### Step: 2

Description of issue
The link to download IdFix no longer works:  https://www.microsoft.com/en-us/download/details.aspx?id=36832

IdFix is now available on Github.

Repro steps:

1.
1.
1.

**Comment by AnnetteGill** [comment]
IdFix setup program is on GitHub here:
https://raw.githubusercontent.com/Microsoft/idfix/master/publish/setup.exe

**Comment by geschwei** [comment]
we are publishing updates to the labs at the end of the day so we do not disrupt existing courses. the change is in the updates to the Labs.
