### ISSUE TITLE
Module 3 - Lab 3 - Exercise 2 T1 step 11 and 14

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/MS-030-Office365Administrator#26]
# Module: 03
#### Step: 11

Description of issue  Outlook is not installed on Lon-CL2 in LOD Logout and log back in as Adatum\Holly to Lon-Cl1 and configure next steps  from there 

Step 14 - Holly was created with the new domain name not the onmicrosoft.com one.

**Comment by geschwei** [comment]
Reviewing this issue. I will post my findings as soon as I finish testing.

**Comment by geschwei** [comment]
Hello Mike, I have addressed this issue. Thank you for catching this. It is greatly appreciated.
