### ISSUE TITLE
Mod 10 EX2 LON-CL2 not domain joined in LOD

### ISSUE THREAD

**Issue by MikeVeschi** [MicrosoftLearning/MS-030-Office365Administrator#27]
# Module: 10
#### Step: 1

Description of issue: In LOD Lon-cl2 is not domain joined, 

Repro steps:

1.Login as Admin local
1.
1.

**Comment by geschwei** [comment]
Reviewing this issue. I will post my findings as soon as I finish testing.

**Comment by geschwei** [comment]
Hello, I have found your issue in question and have resolved it. LOD should be updating the lab to reflect the change. Thank you for catching this issue.
