### ISSUE TITLE
User Conflict

### ISSUE THREAD

**Issue by sarajfMCT** [MicrosoftLearning/MS-030-Office365Administrator#29]
# Module: 06
#### Step: 03

Description of issue
Module 6 Ex 1 Task 4 Step 3 - getting a conflict when creating the contact due to duplicate display name.  Suggest changing the display name of Hai Chu to avoid a conflict with an unlicensed user

**Comment by geschwei** [comment]
Reviewing this issue. I will post my findings as soon as I finish testing.

**Comment by geschwei** [comment]
this issue has been resolved with the last modification.
