### ISSUE TITLE
Vendor Specific References

### ISSUE THREAD

**Issue by rlthompson904** [MicrosoftLearning/MS-030-Office365Administrator#3]
# Module: 00
#### Step: 00

Description of issue
Xtr3m3L@bs used as password still in Modules 5,7,9,10.

Repro steps:

1.
1.
1.

**Comment by geschwei** [comment]
noted modules have been sanitized of the password in question.

**Comment by rlthompson904** [comment]
Close, double-check Exercise 2, Task 1, Step 1. Line 138
