### ISSUE TITLE
Lab9 Ex 2 - Too Classic!

### ISSUE THREAD

**Issue by sarajfMCT** [MicrosoftLearning/MS-030-Office365Administrator#30]
# Module: 09
## Lab/Demo: 09 Ex02

Description of issue
This exercise relies on using the classic site collection page which has been retired and class site navigation to find permissions.  Could do with a refresh to use the current SharePoint Admin center and be based on a Team Site or Communication Site template.

**Comment by WigF1** [comment]
sara, the page should work until December 26, It does need rewriting, but can still be done can it not?

**Comment by sarajfMCT** [comment]
The classic page was not available in the M365 environments I had with last weeks course, hence the comment.  It is still possible to carry out the lab using the modern site collections page but for people new to SharePoint , it is difficult for them to find the find and create the specified site and options.  We did it in my course as a guided exercise with me talking them through every step rather than an lab.

**Comment by mct370770** [comment]
I am currently running this course - and we have passed 26'th of December - and nothing has happened. I am not sure what kind of responsibility that WigF1 is showing in this thread - to aknowledge an will happen after a certain date - and then say there is no reason to do anything yet??????

And YES! - we have managed to use modern instead - but it should be addressed!

**Comment by geschwei** [comment]
I have updated the exercise to reflect the current UI and removed the classic version instructions.
