### ISSUE TITLE
Outstanding pull requests?

### ISSUE THREAD

**Issue by WigF1** [MicrosoftLearning/MS-030-Office365Administrator#31]
I'm going to be going through this material soon but am a little concerned about the number of outstanding pull requests. Is there a reason they are still outstanding?

**Comment by geschwei** [comment]
Hello WigF1, thank you for your concern. the outstanding Pull request is just some housekeeping that needs to be addressed. I will be doing another review of the lab content soon to make sure all lab content will be current with the UI changes.
