### ISSUE TITLE
Module 3 - Lab3 - Exercise 1

### ISSUE THREAD

**Issue by FeckeIT** [MicrosoftLearning/MS-030-Office365Administrator#32]
# Module: 03
#### Step: 01

Description of issue
If we test the Exchange Connectivity, we create issues because the DNS entrys for Exchange Online note complete (no empty CNAME-Record possible) and RPC over HTTP is blocked in Exchange Online. 
Better is, to use the Office 365 / Outlook Connectivity-Test in the lab, this returns no issues

Greets,
Wolfgang

Repro steps:

1.
1.
1.

**Comment by geschwei** [comment]
Hi FeckelIT,
this sounds like a suggestion rather than an issue if you have a suggestion for the lab. please submit a pull request so I can review it.
