### ISSUE TITLE
Module 07, Lab7/Exercise1 Task 2 Step 9

### ISSUE THREAD

**Issue by FeckeIT** [MicrosoftLearning/MS-030-Office365Administrator#33]
# Module: 07
#### Step: 09

Description of issue:
In the Transport Rule is in the lab the condition "Is a member of.." select, but if we select Megan Bowen - and not a distribution group -  as a recipient, the condition "The recipient is.." must be use.

Greets,

Wolfgang 

Repro steps:

1.
1.
1.

**Comment by geschwei** [comment]
thank you for this call out. issue has been resolved.
