### ISSUE TITLE
Module 11 - Lab 11 - Exercise 1 - Creating Sensitivity Labels

### ISSUE THREAD

**Issue by AustinP00** [MicrosoftLearning/MS-030-Office365Administrator#34]
# Module: 11
### Exercise: 1

Description of issue
Changing primary address of an active group. 

Repro steps:

1. Added work around as a note for the users

**Comment by geschwei** [comment]
Hi Austin, where was this added workaround that you speaking of?

**Comment by Johnny-5-Alive77** [comment]
Between steps 13 and 14. 

After our created group PND shows as an Active group, press on the newly created group and select under the email address section the edit button.

Next, we need to request/approve the used address as the primary address.

Select the horizontal elipses shown under the alias section and click on change to primary email.

The PND address used should now be the primary email address.
