### ISSUE TITLE
IDFix problems

### ISSUE THREAD

**Issue by ITBlandMCT** [MicrosoftLearning/MS-030-Office365Administrator#38]
# Module: 04
#### Step: All

Description of issue
1. LON-DC1 does not have .NET installed (Shouldn't we use CL1, anyway?)
1. IDFix does not show the Maj Hojski error.
1. IDFix after v2.2 (current is v2.3) does not show both duplicates (only Lara shows, not Logan), making correction impossible.
1. IDFix installs into a folder in %AppData%, making the log file very difficult to locate.

Possible Work-arounds:
1. Use CL1
2. Remove Maj Hojski instructions from the lab.
3. Use v1.11 so that the duplicates show.
4. Download the .exe and run it directly so that the log file is created in the downloads folder.
Link to direct download of IDFix v1.11: https://github.com/microsoft/idfix/raw/master/publish/Application%20Files/IdFix_2_0_0_0/IdFix.exe
or, if you click the Undo button and change the file to "***.txt**" you can then right-click and open the log file from inside the Undo open folder window.

**Comment by geschwei** [comment]
this issue was resolved with the last update.

**Comment by WigF1** [comment]
@geschwei - This issue was not resolved with the last update. I encountered this issue yesterday. It is also still listed as a bug on the IdFix GitHub Issues page.

**Comment by geschwei** [comment]
@WigF1 that resolution for another issue. I went ahead and removed Maj from the notes and replaced the existing link to the newer version of idfix with link you provided.
