### ISSUE TITLE
Module 2, Lab 2, Exercise 4 - Download link for 'Microsoft Online Services Sign-In Assistant for IT Professionals RTW needs to be updated'

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-030-Office365Administrator#39]
# Module: 02
## Lab/Demo: 02
Exercise 4
#### Step: 02

Description of issue download link for 'Microsoft Online Services Sign-In Assistant for IT Professionals RTW needs to be updated'

Current link: http://aka.ms/t01i1o  (https://www.microsoft.com/en-us/download/details.aspx?id=41950) is no longer active and gives a 404 not found.

Now available here: https://www.microsoft.com/en-us/download/details.aspx?id=28177

**Comment by craigbeeremct** [comment]
Alternatively, since the tool is not required for Windows 8 and later, remove all references to it from the lab.

**Comment by Johnny-5-Alive77** [comment]
Relates to #42, download links for the sign-in assistant are deprecated.

**Comment by geschwei** [comment]
The issue has been resolved and the lab has been updated to reflect the change.

**Comment by AngelGV** [comment]
What is now the link to install it or what is the new mechanics?

**Comment by m-minning** [comment]
The link https://download.microsoft.com/download/5/0/1/5017D39B-8E29-48C8-91A8-8D0E4968E6D4/en/msoidcli_64.msi stopped working for us today, it worked yesterday.

I found a link to the [x86 version](https://download.microsoft.com/download/7/1/E/71EF1D05-A42C-4A1F-8162-96494B5E615C/msoidcli_32bit.msi) [here](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-microsoft-365-powershell?view=o365-worldwide#connect-with-the-microsoft-azure-active-directory-module-for-windows-powershell)

**Comment by AngelGV** [comment]
> The link https://download.microsoft.com/download/5/0/1/5017D39B-8E29-48C8-91A8-8D0E4968E6D4/en/msoidcli_64.msi stopped working for us today, it worked yesterday.
> 
> I found a link to the [x86 version](https://download.microsoft.com/download/7/1/E/71EF1D05-A42C-4A1F-8162-96494B5E615C/msoidcli_32bit.msi) [here](https://docs.microsoft.com/en-us/microsoft-365/enterprise/connect-to-microsoft-365-powershell?view=o365-worldwide#connect-with-the-microsoft-azure-active-directory-module-for-windows-powershell)

Thank you very much!!!!

**Comment by webbie003** [comment]
x64 URL: https://download.microsoft.com/download/7/1/E/71EF1D05-A42C-4A1F-8162-96494B5E615C/msoidcli_64bit.msi

**Comment by github-man** [comment]
Thanks for posting the link. 
The removal for this file breaks the M365 integration set up for all Windows Server 2012R2 and Windows Server 2016 servers with the Essentials role installed.

Putting some keywords here for anyone searching for a fix:
"There was an issue configuring the integration"
"Make sure the computer is connected to the internet and then try again"
Windows Server Essentials Role Office 365 Microsoft 365 integration fails
Fix: download and install msoidcli_64bit.msi  from here: https://download.microsoft.com/download/7/1/E/71EF1D05-A42C-4A1F-8162-96494B5E615C/msoidcli_64bit.msi  then re-run the integration wizard.

**Comment by kirilvalev** [comment]
This also breake the installation of the "Dynamics 365 Report Authoring Extension".

**Comment by Bun-Bun** [comment]
Ended up here after a lot of searching (final search was simply "ID 41950")

Server2012R2 Essentials M365 Integration not working. github-man's post was not enough to find this in my previous searches. The actual errors in the log file that are specifically related to download link to msoidcli being broken are:

failed to install MSOIDCRL, 0 times remaining, exp = Microsoft.WindowsServerSolutions.MailService.MailServiceException: The remote server returned an error: (404) Not Found.


Hopefully this helps someone save hours of googling...
