### ISSUE TITLE
DNS IP Record Double FQDN Entry

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/MS-030-Office365Administrator#4]
# Module 1: Planning and provisioning Office 365
#### Step: 27 

Description of issue:

"In the New Host box, Under Name, type the name of the external name server as provided by the Lab hosting provider."

If you follow the directions as written here, your record for the IP would have a double entry in the FQDN. For example, let's say we had a provided domain of adatum123.customdomain.com.  If we put the name in this field, it would read something like this:
![image](https://user-images.githubusercontent.com/41710326/73195025-c33c6580-40f2-11ea-8f97-62cc72e90bf8.png)

What I suspect is that the directions mean to state that the name field should be left blank, so that it takes on the name of the parent, as shown here:

![image](https://user-images.githubusercontent.com/41710326/73195192-0c8cb500-40f3-11ea-853d-99f85d3f8342.png)

which then shows as:

![image](https://user-images.githubusercontent.com/41710326/73195219-18787700-40f3-11ea-8a7f-354749dd8e10.png)

Repro steps:

Run Exercise 2: Configuring a custom domain
Task 1: Add the custom domain and set up the DNS server.

**Comment by geschwei** [comment]
thank you for the identified problem addressing now.
