### ISSUE TITLE
Module 10 - Lab 10 - Exercise 3 - Configuring Microsoft 365 groups Task 2 Step 8

### ISSUE THREAD

**Issue by dbarker19** [MicrosoftLearning/MS-030-Office365Administrator#41]
# Module: 10
#### Step: 08

Description of issue
PowerShell command is not correct.
Current -  Add-UnifiedGroupLinks "Planning" –Links Admin@C –LinkType Owner
Correct -  Add-UnifiedGroupLinks "Planning" –Links  admin@M365xZZZZZZ.onmicrosoft.com –LinkType Owner

**Comment by geschwei** [comment]
thank you, i have resolved this issue.
