### ISSUE TITLE
Is this repo being maintained?

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/MS-030-Office365Administrator#44]
There seems to be many outstanding Issues/Pull requests and coupled with the changes to many of the Admin portals in 365, the lab instructions are very out of date.

Are any of the admins doing stuff in here?

**Comment by geschwei** [comment]
Hi DJ,

I am working to update these issues thank you for your patience.

**Comment by djcmct** [comment]
Its ok asking us to be patient, but some of these issue were raised last year and are still incorrect despite there being pull requests waiting to fix them.....
