### ISSUE TITLE
Lab 2 Ex 3 corrections

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/MS-030-Office365Administrator#54]
# Module: 03
#### Step: VArious

instructions don't match portal

Repro steps:

Step 6 should read
In the Assign owners window, select the + Assign Owners field, which displays the list of active users. Select Alan Yoo and then select Add (1). On the Assign Owner window select Next, and on the Add members page select Next.
Step 24 should read
In the Owners window, select +Add owners. This displays the list of current users.
Step 25 should read
In the list of users, select Libby Hayward and then select Add (1).
Step 26 should read
In the Owners window, select the X in the upper right-hand corner to close the window
Step 27 should read
In the Active groups list, select the Accounts Receivable group, which opens a window for the group, then select the Members tab and then select View all and manage members to add members to the group.
Step 28 should read
In the Members window, select +Add members. This displays the list of current users.
Step 29 should read
In the list of users, select Adam Hobbs and Libby Hayward and then select Add (2).
Step 30 should read
In the Members window, select the X in the upper right-hand corner to close the window.
Step 31 should read
In the Active Groups window select the Microsoft 365 tab.

**Comment by geschwei** [comment]
resolved with latest updates.
