### ISSUE TITLE
Mod 2 Ex 4 Corrections

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/MS-030-Office365Administrator#55]
# Module: 02
#### Step: 24

Instructions using Classic Exchange Admin, Portal loads New version by default

Repro steps:

Step 24 should read
In the Exchange admin center, in the left-hand navigation pane, select Mailboxes under recipients. Review the mailboxes. Note that no Exchange mailbox was created for any of the unlicensed users.

**Comment by geschwei** [comment]
resolved with latest updates.
