### ISSUE TITLE
Mod 3 Ex corrections required

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/MS-030-Office365Administrator#56]
# Module: 03
#### Step: various

Instructions don't match interface

Repro steps:

Step 5 should read
On the Office 365 page, select the box that says: Exchange Online Custom Domains DNS Connectivity Test
Step 6 Should read
On the Exchange Online Custom Domains DNS Connectivity Test page, enter the following information:

**Comment by geschwei** [comment]
resolved with latest updates.
