### ISSUE TITLE
Mod 4 IDFIX task is still a mess....

### ISSUE THREAD

**Issue by djcmct** [MicrosoftLearning/MS-030-Office365Administrator#57]
# Module: 4
#### Step: all

IDFIX task doesn't work, need to be fixed or removed

Repro steps:

After running .\createproblemusers.ps1 in step 4 we are told that 3 users  are changed
Klemen Sic. Update the UserPrincipalName for Klemen to include an extra "@" character.
Lara Raisic. Update the emailAddress attribute for Lara to lara@adatum.com.
Logan Boyle. Update the emailAddress attribute for Logan to logan@adatum.com.

But Powershell reports 5 users are updated
![Capture](https://user-images.githubusercontent.com/47788394/124264395-4e156100-db2c-11eb-8a1a-613ceadb967e.PNG)

Task 3 Step 11 then reminds us that Maj's account was broken, PS reports that, but the earlier instructions make no reference to Maj, and the instruction to fix Maj's account cannot be performed.
Step 12 then asks you to fix Klemen's account, again, this cannot be performed
The following steps in regard to the log file cannot be performed.
![Capture1](https://user-images.githubusercontent.com/47788394/124265410-8a958c80-db2d-11eb-971e-329108e5e986.PNG)

This has been raised in more than one issue that have been closed off claiming to be resolved.

Could this exercise either be fixed or removed?

**Comment by geschwei** [comment]
This issue is dealing with a bug with the current version of IDFIX. There has been a note added inside the lab and references how to resolve the issue.
