### ISSUE TITLE
Updates anticipated to bring instructions inline with updated Office365 Admin UI?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MS-030-Office365Administrator#8]
# Module: All
#### Step: All

Description of issue
Office365 Admin UI has changed since last Instructions release, is there a semi-annual review scheduled at some point to bring .mds into line with new menus/options/phrasing?

**Comment by geschwei** [comment]
edits will be reviewed and updated as on a quarterly basis.

**Comment by WigF1** [comment]
So, what happened to the quarterly updates? They don't seem to have occurred and there are outstanding pull requests.
